baseURL: https://qahello415.github.com/
languageCode: en-us
title: QA Hello | Testing, Research Services
theme: fresh
# googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy
  description: QAhello.com - Providing Software QA Testing, Research and Data QC, and Invoice Management services.
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/fresh.svg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Quality Assurance, our main ingrediant!
    # Hero subtitle (optional)
    subtitle: We're here to serve your needs because we care about your results.
    # Button text
    buttontext: Get In Touch
    # Where the main hero button links to
    buttonlink: "#"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About Us
    url: /
  - title: Services
    url: /
  - title: Extras
    sublinks:
    - title: Good Works
      url: /
    - title: Favorite Tools
      url: /
    - title: Choice Affiliates
      url: /
  - title: Blog
    url: /
  - title: Contact Us
    url: Https://www.linkedin.com/sfbayrose
    button: true

  section1:
    title: QA HELLO
    subtitle: We're all About the quality that makes things count!
    tiles:
    - title: QA Testing
      icon: mouse-globe
      text: Advanced manual software and SaaS QA Testing services
    - title: Data Research and QC
      icon: laptop-cloud
      text: Specializing in industrial data research and verification processes
    - title: Orders & Invoicing
      icon: plug-cloud
      text: Ecommerce order management, Harvest Invoicing superpowers 
  section2:
    title: You're here because you want the best
    subtitle: And we know it!
    features:
    - title: Powerful assistance you can trust
      text: Let our years of experience pay off for you. Rose and her small team have over a decade of experience. We can lighten your load, so you can focus on top priorities!
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Manual software QA testing services, mobile and desktop, A11Y focused
      text: Our small QA team has experience going back to dialup days, with 1st QA experiences on the Netwcape web browser partnership with work at Pacifi Bell Internet. More recently our QA team members have experience centering around SaaS startup work with apps built on Ruby. Let's get together and get those bugs out and crush on roadmap goals.
      icon: doc-sync
    - title: Stellar eCom management service, Advanced Harvest Invoicing
      text: Expert handling for orders, invoicng, and more. Rosalie is very conciencious, diligent, and dedicated to getting every task done exactly to your specifications. Extend your reach and grow your success by adding her tallents to your arsenal of resources. Your Orders, your Research Projects, your Harvest Invoicing - put it all in caring hands and rest assured! 
      icon: mobile-feed
  section3:
    title: We Work Hard for you @ QAhello
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get With Us!
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: fresh-white-alt.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/lucperkins/github-fresh
      # Icons are from Font Awesome
      icon: github
    - link: https://dribbble.com/#
      icon: dribbble
    - link: https://facebook.com/#
      icon: facebook
    - link: https://twitter.com/lucperkins
      icon: twitter
    - link: https://bitbucket.org/#
      icon: bitbucket
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second